name: Wombo API (Status Check)

on: [pull_request]

env:
  CONTAINER_IMAGE: tfsantosbr/wombo.api
  CLUSTER_NAME: wombo-sandbox-cluster
  TASK_NAME: production-api-task
  TASK_DEFINITION_PATH: .aws/task-definition.production.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal